# Generated by Django 4.0.2 on 2022-04-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbottle',
            name='Supplied_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myinventoryapp.supplier'),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='Current_Quantity',
            field=models.IntegerField(),
        ),
    ]
